version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=supersecretDbPassword
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
  django-backend:
    build: .
    # image: python:3.9-slim
    depends_on:
      - db
    tty: true
    working_dir: /work
    command: ./manage.py runserver 0.0.0.0:8000
    networks:
      - backend
    ports:
      - 8000:8000
    volumes:
      - .:/work
    environment:
      - DATABASE_URL=postgres://postgres:supersecretDbPassword@db:5432/postgres
    
networks:
  backend:

volumes:
  db-data:
