version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_PASSWORD=supersecretDbPassword
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  # django-backend:


networks:
  backend:

volumes:
  db-data: