version: '3.8'
services:
  django-backend:
    build: .
    # image: python:3.9-slim
    tty: true
    working_dir: /work
    command: ./manage.py runserver 0.0.0.0:8000
    networks:
      - backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/work
    
networks:
  backend:
