# Generated by Django 3.2 on 2022-02-12 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('memory', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(512)])),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('A', 'Active'), ('D', 'Done')], default=('S', 'Scheduled'), max_length=1)),
                ('provision_job_id', models.UUIDField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('duration_in_seconds', models.PositiveIntegerField(default=3600, validators=[django.core.validators.MaxValueValidator(3600)])),
                ('needed_capacity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationcapacity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
