# Generated by Django 3.2 on 2022-02-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
